### ISSUE TITLE
Sidebery navbar panel icons are displayed as flipped unless "Show in one line" is turned on

### ISSUE THREAD

**Issue by qyurila** [KiKaraage/ArcWTF#10]
## Description

Panel icons on Sidebery navbar are displayed as flipped if the setting is "horizontal + 'Show navigation bar in one line' turned off" or "vertical". It doesn't happen with "horizontal + 'Show navigation bar in one line' turned on" settings.

What especially doesn't make sense to me is that the navbar layout shown in the preview screenshot on the README seems to be possible only when the "Show in one line" option is turned off, because one-lined navbar seems it doesn't really respect the elements list on the settings.

The screenshots below are taken with a slightly modified CSS config, but the issue occurs with the official config too.

### Environment

- Floorp 11.10.1 (Firefox 115.8.0)
- Sidebery 5.1.1

## Screenshots

![image](https://github.com/KiKaraage/ArcWTF/assets/68494132/71b886b6-4485-4cb8-b871-40716a48f91a)
![image](https://github.com/KiKaraage/ArcWTF/assets/68494132/06e1d842-475b-4c4f-a996-ae375b56713d)
![image](https://github.com/KiKaraage/ArcWTF/assets/68494132/ce640f52-385f-403c-9fcb-4eb2ba6ea4fb)

**Comment by qyurila** [comment]
(Obvious but) resolved by fixing this line:

https://github.com/KiKaraage/ArcWTF/blob/6eef0115ae9db1ec0965f6e899a3a41e73feff71/sidebery/sidebery-css#L12

to the following:

```css
.NavigationBar .nav-item:not([data-class="panel"]) {
```

**Comment by KiKaraage** [comment]
Thank you for the feedback! I hope the current CSS fixes it well
