### ISSUE TITLE
Popup sideberry renders below browser content

### ISSUE THREAD

**Issue by FabiSahne** [KiKaraage/ArcWTF#101]
**Describe the bug**
When hovering to open sideberry, I can only see the leftmost edge of it. I assume the rest is hidden behind the browser content.

**Screenshots**
![image](https://github.com/user-attachments/assets/ce499bc0-c87d-49cc-a0b5-e770f728057d)

**Desktop:**
 - OS: Windows 11 23H2
 - Firefox Version 133.0b1 Dev Edition

**Comment by datguypiko** [comment]
Add this at the end of userChrome.css

```css
#sidebar-box {
  z-index: 4;
}
```
