### ISSUE TITLE
CSS suddenly not displaying properly after updating Firefox

### ISSUE THREAD

**Issue by Ein420** [KiKaraage/ArcWTF#102]
**Description**
Rounded borders around page are missing and no longer display after updating Firefox

**To Reproduce**
update to 132.0 (64-bit)

**Expected behavior**
Borders display normally, around browser window

**Screenshots**
![image](https://github.com/user-attachments/assets/8081c778-8dfb-49f8-a5fd-91595194ed01)
![image](https://github.com/user-attachments/assets/fe47392e-91a6-44db-af0a-e4e78bad0712)
![image](https://github.com/user-attachments/assets/56862231-7bb2-489c-b5cd-7cc7b9880f72)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Firefox Version: 132.0 (64-bit)

**Comment by scattagain** [comment]
have this same issue, no idea what could've changed to break the theme like that (also arch linux on 132.0)

**Comment by datguypiko** [comment]
I dont think `#appcontent` is a thing anymore.

Open browser.css file, find `#appcontent` and replace it with for example `#tabbrowser-tabbox`
