### ISSUE TITLE
Minimize, maximize and close button not working after latest update

### ISSUE THREAD

**Issue by groovitz** [KiKaraage/ArcWTF#105]
![ezgif-4-07e70f9df8](https://github.com/user-attachments/assets/2507a42d-30c0-4bf0-b93a-eb99e8591df7)

As you can see in the uploaded gif, the toolbar buttons won't work. It doesn't matter if the firefox window is open or not. I disabled sideberry and it worked fine.

 - OS: Windows
 - Firefox Version 133.0

**Comment by groovitz** [comment]
By toolbar, I mean the minimize, maximize and close buttons

**Comment by Aboniabo** [comment]
Yeah same here

**Comment by gdude2002** [comment]
Worth noting this problem is not unique to ArcWTF, EdgyArc and other userchrome styles also have this problem since the recent Firefox update

**Comment by KiKaraage** [comment]
Wait lemme look up the issue and see how edge-frfox fix it (if there's any).
Hoping this can be solved within one week 🙏

**Comment by KiKaraage** [comment]
Please try modifying urlbar, tabbar and hide-tabs-bar based on my latest three commits and see if it works again.

**Comment by gdude2002** [comment]
I can confirm this you've fixed this problem. Good work!

**Comment by SEGFAULT3102** [comment]
After applying this fix I can't seem to hide my tab bar anymore.

**Comment by SEGFAULT3102** [comment]
> After applying this fix I can't seem to hide my tab bar anymore.

Nevermind, I had to add uc.tweak.hide-tabs-bar to the about:config page, and then restart firefox.
