### ISSUE TITLE
Tabs bar not hidden by default

### ISSUE THREAD

**Issue by Roconx** [KiKaraage/ArcWTF#106]
**Describe the bug**
The default tabs bar is not hidden by default after commit 5e952b730168676137dc5a6ab12009a65b37eb7c

**To Reproduce**
Clone repo and restart firefox

**Expected behavior**
Default tabs bar hidden by default on firefox

**Desktop (please complete the following information):**
 - OS: macOS
 - Firefox Version 133.0

**Additional context**
In the mentioned commit you appear to have added the "uc.tweak.hide-tabs-bar.no-window-controls" preference and tabs won't hide if it is not enabled. It took me a while to figure out why it was not working. Maybe consider adding it to the readme or enabling it by default?

**Comment by KiKaraage** [comment]
Well if you activated Sidebery the horizontal tabs should be hidden by default.

**Comment by KiKaraage** [comment]
Pardon me. Please try it now and let me know if it's worked by default again!

**Comment by Roconx** [comment]
Yes, that fixed it!
