### ISSUE TITLE
Missing Firefox View button?

### ISSUE THREAD

**Issue by lnoss** [KiKaraage/ArcWTF#13]
Hey, thanks for you hard work, the reskin is great! I just want to know if you see your "Firefow View" button on your Firefox with ArcWTF? I looked a bit in the source code, and it doesn't look like you're hiding it. I'm looking for the reason for its absence on my side, whether it's the redesign or perhaps some preferences in "config" that need adjusting, since "Firefow View" got upgraded in v123.

**Comment by KiKaraage** [comment]
You can add it to the navbar from the Customize Toolbar menu.
![gambar](https://github.com/KiKaraage/ArcWTF/assets/10529881/c540b7e3-3a08-4a11-9019-420d1b65a6c2)
![gambar](https://github.com/KiKaraage/ArcWTF/assets/10529881/c5c89246-3f31-4f3a-aaa6-33d95aacde0e)

**Comment by lnoss** [comment]
How, you are right, it was really hidden on the top left tab bar. Thanks!
