### ISSUE TITLE
Is there a way to make the corners rounded of the hover to extend sidebery bar.

### ISSUE THREAD

**Issue by anoshione** [KiKaraage/ArcWTF#15]
![agesdfg](https://github.com/KiKaraage/ArcWTF/assets/81085871/2d4148ef-bb3e-4222-b6d4-39974a0a13bc)

**Comment by KiKaraage** [comment]
Add this to sidebar.css: 

```#sidebar{border-radius: 10px !important; margin-bottom: var(--uc-tweak-rounded-corners-padding) !important;}```

You can also add this line to Sidebery style editor: `#root.root {padding-top: 8px;}`

**Comment by anoshione** [comment]
That didnt fix it, normal extended tab when userchrome is on , thats fine . but the hover to extend tab bar shows those corners.

**Comment by KiKaraage** [comment]
Care to elaborate what do you want? Because border-radius on #sidebar should've fixed the sidebar already.

You can also replace sidebar.css file with the latest version from this repo manually.

![gambar](https://github.com/KiKaraage/ArcWTF/assets/10529881/1c828b11-21c4-4dc7-930b-8686a69c988f)

**Comment by KiKaraage** [comment]
Hi, I made [a commit related to this issue](https://github.com/KiKaraage/ArcWTF/commit/3f7de6c3efb07063c40d9201016e526f2d2512a8) yesterday. You might want to try the latest sidebar.css file and see if that's working for you
