### ISSUE TITLE
--toolbar-bgcolor makes the url suggestion bar have transparent background

### ISSUE THREAD

**Issue by susanthenerd** [KiKaraage/ArcWTF#16]
Hello!

I'm running the main branch and while playing around with it I found that URL suggestion pop-out has a transparent background. 

This is most probably due to the use of `--toolbar-bgcolor` when setting the background, variable which on default configuration of Adaptive Tab Bar Color is set to be transparent. I believe ATBC has a separate CSS variable that can be used only for the URL bar, but I'm not sure. 

This issue was introduced in commit 54413902c58b9792a7ee1150ce82b3e82453db24

**Comment by KiKaraage** [comment]
Okay can you help test it by replacing `--toolbar-bgcolor` with `--tabpanel-background-color`? I'm currently not using Adaptive Tab Bar Color now

**Comment by KiKaraage** [comment]
....also I think "same color" would be more accurate than "transparent". You can change findbar color from "toolbar" section on the ATBC's addon settings.
![gambar](https://github.com/KiKaraage/ArcWTF/assets/10529881/a02920a6-9e3b-443d-8881-bd83b1086edc)

**Comment by KiKaraage** [comment]
> same color with the application menu

I searched on [edge-frfox color.css](https://github.com/bmFtZQ/edge-frfox/blob/main/chrome/global/colors.css) and seems like both menu and panels (so, context menu should be included here?) uses `--arrowpanel-background-color`. Some other things like popup dialogs uses that parameter too

**Comment by jacksonsamuelmoore** [comment]
Ran into this problem and did some testing: it appears the test commit ([08423c9](https://github.com/KiKaraage/ArcWTF/commit/08423c9c623cb1a5e9c09a46dac53bba08018575)) actually sort of breaks things. I found that it results in a semi-transparent pop-out with or without ATBC. Reverting it fixes the bar when not using ATBC. When using ATBC, the pop-out is fully transparent by default, but increasing the `background` value in the toolbar settings of ATBC by one stop seems to fix it completely:
![image](https://github.com/KiKaraage/ArcWTF/assets/14311315/777f8a45-2ce4-48da-a5f7-36031238cc8b)

Some screenshots:

With `--arrowpanel-background-color` **without** ATBC:
![image](https://github.com/KiKaraage/ArcWTF/assets/14311315/90f4dfdd-3bfa-4ed8-a95a-5b1c0b678624)

With `--arrowpanel-background-color` **with** ATBC and toolbar fix applied:
![image](https://github.com/KiKaraage/ArcWTF/assets/14311315/a757229a-4fea-4f89-a6fc-a09fa4562e74)

With `--toolbar-bgcolor`  **without** ATBC:
![image](https://github.com/KiKaraage/ArcWTF/assets/14311315/36b19b75-602d-4d4a-be5c-5d7c070cb418)

With `--arrowpanel-background-color` **with** ATBC and toolbar settings fix **not** applied:
![image](https://github.com/KiKaraage/ArcWTF/assets/14311315/f95f9f56-84da-4108-95a0-e2822981dd8a)

With `--arrowpanel-background-color` **with** ATBC and toolbar settings fix applied:
![image](https://github.com/KiKaraage/ArcWTF/assets/14311315/33c73e00-9f1d-4ce0-92f2-43579e2fe629)

I'm testing with the Firefox Flatpak on Fedora 39, but I think it should be the same on Windows

**Comment by susanthenerd** [comment]
Hello! I can confirm increasing the toolbar background variable in the settings now fixes the issue. Thank you.

**Comment by PixsaOJ** [comment]
`--arrowpanel-background-color` is supposed to be `--arrowpanel-background` Thats the problem !
