### ISSUE TITLE
Flickering sidebar when hovering

### ISSUE THREAD

**Issue by ishid4** [KiKaraage/ArcWTF#17]
`#main-window[sizemode="maximized"] #sidebar-box{ 
  --uc-sidebar-width: 0.6rem;
  }

#main-window[sizemode="fullscreen"] #sidebar-box{ --uc-sidebar-width: 0.6rem; }`
tweaks/sidebar.css

For fixing the flickering, 0.6rem is hot spot for me.

**Comment by KiKaraage** [comment]
Thank you for the suggestion!

I still think the sidebar will be flickered if you hover on around 1px **right after 0.6rem** tho, because I set the opacity directly to 1% when collapsing the sidebar. Hence, to "fix" this, I prolonged the delay duration to 400ms. I hope it helps

**Comment by ishid4** [comment]
Yes, it helps the flickering problem but it creates another problem such as when there is content on the left of the page you can not click it because of the sidebar appearing. I'll try to find a more suiting fix.

**Comment by KiKaraage** [comment]
> when there is content on the left of the page you can not click it because of the sidebar appearing

Yeah you need to let it went hidden first before going to left side of the site you're visiting... Hence in the start of this I prefer using 100ms delay time.
