### ISSUE TITLE
How to change the accent

### ISSUE THREAD

**Issue by daFoggo** [KiKaraage/ArcWTF#18]
Hi. I just want to know how to change the color accent like you did in the preview image?
I tried Firefox color but it only change the background color not the navigation bar. Thanks
![image](https://github.com/KiKaraage/ArcWTF/assets/108665939/3de6a573-956c-4071-bfe4-50d373f6a0c2)

**Comment by daFoggo** [comment]
![image](https://github.com/KiKaraage/ArcWTF/assets/108665939/223894e8-677a-4feb-9722-ceef4b4dbfb4)
I tried changing toolbar color but it didnt work at all

**Comment by KiKaraage** [comment]
....try Proton theme?

![gambar](https://github.com/KiKaraage/ArcWTF/assets/10529881/3204b4b0-aa99-44d3-bf3e-1b0ed8500b3b)

but no it should kinda look the same....

**Comment by daFoggo** [comment]
ok thats work. btw is there any way to make the sidebar has rounded conners?

**Comment by KiKaraage** [comment]
Previously I applied rounded corner only on the bottom right side of #sidebar and top right side of #sidebar-header, and then by the commit above I added rounded corner on bottom left side too.

1) If you want to add rounded corner on the remaining side, you can add `border-top-left-radius: var(--uc-tweak-rounded-corners-radius) !important;`to #sidebar-header (line 75);

2) Or if you only want rounded corners on all side of #sidebar and not #sidebar-header, you can just replace `border-bottom-right-radius` and `border-bottom-left-radius` to `border-radius` in #sidebar (line 6).

**Comment by daFoggo** [comment]
thanks

**Comment by daFoggo** [comment]
Sorry but which file were you referring to? I cant find it. Also what is the attribute of the background color of this button I want to config it. Thanks 
![image](https://github.com/KiKaraage/ArcWTF/assets/108665939/1724c75c-d762-4f8f-8bed-7af97e7dd8dd)

**Comment by KiKaraage** [comment]
I was referring to [tweaks/sidebar.css](https://github.com/KiKaraage/ArcWTF/blob/main/tweaks/sidebar.css) 

Here is the structure
![gambar](https://github.com/KiKaraage/ArcWTF/assets/10529881/01fef503-f6c6-4a4c-a057-19da1c4255dc)

And command the location you asked would be 
```
.Sidebar .tool-btn {
  background-color: (insert the color code);
}
```
![gambar](https://github.com/KiKaraage/ArcWTF/assets/10529881/f283467a-2e22-4198-8f1a-680b050b6894)

**Comment by daFoggo** [comment]
do you have a discord I want to dm you for some stuffs. My reddit dont
allow me to send message. sorry

Vào Th 6, 1 thg 3, 2024 vào lúc 05:25 KiKaraage ***@***.***>
đã viết:

**Comment by KiKaraage** [comment]
Sure, @kigeprak
