### ISSUE TITLE
No Dark Mode support?

### ISSUE THREAD

**Issue by AryanVerma1024** [KiKaraage/ArcWTF#2]
The icons for the different ui elements which should change to white are not doing so when using this theme
eg :
![image](https://github.com/KiKaraage/ArcWTF/assets/80571430/26e95cee-2f8a-4a61-9c10-9609032c0c92)

**Comment by LuanderFarias** [comment]
that's strange, it works 100% for me. on light, dark, rose or any theme i chose.

**Comment by KiKaraage** [comment]
Have you tried to enable `svg.context-properties.content.enabled` in about:config?
You can also use other themes that have no clashed colors (dark tab bar with light toolbar and urlbar, or vice versa)

**Comment by AryanVerma1024** [comment]
I am extremely sorry for wasting your time.
Thanks :)

**Comment by KiKaraage** [comment]
Your welcome! Thanks to your concerns I finally added it on the readme too
