### ISSUE TITLE
Is there a way to change the padding in navigation bar?

### ISSUE THREAD

**Issue by petar-kovac** [KiKaraage/ArcWTF#21]
Can we make the spacing here smaller?
Or the width wider?
![image](https://github.com/KiKaraage/ArcWTF/assets/105488397/62377275-3f4d-45cb-8235-a87a1a2d3f14)

**Comment by KiKaraage** [comment]
> Can we make spacing here smaller?

Yes, by decreasing #tabs-margin in Sidebery style config.

> Or the width wider?

You can add new Boolean parameter `uc.tweaks.longer-sidebar` to expand the sidebar to 250px, or edit the default sidebar length on sidebar.css.

Also pardon for the previous issues with sidebery CSS config, I haven't updated it. I'm doing it right now, complete with updating the release version + updating the Readme file.

**Comment by petar-kovac** [comment]
Tried the solution you suggested.

I should be more precise, could we adjust just the padding (left and right, make it smaller) or have the tab width to be longer (not the whole side bar)?

If not, I'm happy with the current state just wanted to see If this could be changed.

It goes without say, thanks for this project/ideas -> you are the hero!

**Comment by KiKaraage** [comment]
Sadly no, #tabs-margin does limit the horizontal length of the tabs, affecting both pinned and unpinned tabs.

I tried to split #tabs-margin into four values to see if each side could be given different margin sizes... and it doesn't work, while also making all tabs loses their inner margins/paddings.

![gambar](https://github.com/KiKaraage/ArcWTF/assets/10529881/a3160e62-6129-4e62-97be-e23f9cc8a7eb)

First value = right margin, second value = bottom margin, third value = left margin/tabs indent, and adding a fourth value results in zero margins on all sides.

**Comment by petar-kovac** [comment]
Thanks @KiKaraage for the explanation, I'll close this issue.
