### ISSUE TITLE
[Minor-Bug] Search popup window

### ISSUE THREAD

**Issue by petar-kovac** [KiKaraage/ArcWTF#22]
Hi again :) 

In the how-to enable popup window when searching there is a typo (I guess):
![image](https://github.com/KiKaraage/ArcWTF/assets/105488397/d25bdddb-b131-41a2-9fbc-94bc14d9be20)
![image](https://github.com/KiKaraage/ArcWTF/assets/105488397/eb8751de-b223-4aad-88e6-a805a3928210)

I guess it should be _"uc.**tweak**.popup-search"_ in the documentation.

**Comment by Enigma1309** [comment]
![image](https://github.com/KiKaraage/ArcWTF/assets/94917588/52e98c76-3cb5-4293-b98a-263093ae9ab7)
Also i'm experiencing transparent look, on both firefox and librewolf in linux.

**Comment by petar-kovac** [comment]
Just checked, I have the same issue.

**Comment by jacksonsamuelmoore** [comment]
I fixed the transparent look by reverting at commit that changed
`#urlbar[focused="true"] > #urlbar-background {background: var(--toolbar-bgcolor) !important;}`
to 
`#urlbar[focused="true"] > #urlbar-background {background: var(--arrowpanel-background-color) !important;}`

Manually replacing the second line with the first in `toolbar/urlbar.css` seems to solve the problem

**Comment by PixsaOJ** [comment]
@jacksonsamuelmoore That did not do the trick. Sometimes its transparent, sometimes its not.

**Comment by jacksonsamuelmoore** [comment]
@PixsaOJ Very odd - did you check out my more detailed testing? Additionally, I found I had to make sure I restarted Firefox between changes. Could you provide any details of your specific setup with the theme and tweaks you've enabled?

**Comment by PixsaOJ** [comment]
I just saw toolbar setting trick, it worked. Cheers 🎉

**Comment by KiKaraage** [comment]
......So, may I close this one? Issues related to URL bar popup transparency can be discussed in #16 and I will let it open.
