### ISSUE TITLE
Tab panel on the wrong side

### ISSUE THREAD

**Issue by redm0re** [KiKaraage/ArcWTF#23]
Hi! Everything seems to work great, expect that sidebery is displayed on the right side of the window. How do I change it to the left without breaking anything? ;)

**Comment by KiKaraage** [comment]
1. Press Alt > (menu bar will shown,) click View > Sidebar > pick other sidebars (Bookmarks, History, or Synced Tabs)
2. Click the sidebar header arrow > Click "Move Sidebar to Left Side"
3. Click the sidebar header arrow > Click Sidebery (or press F1)

**Comment by Kshitij841** [comment]
What is meant in point 2. sidebar header arrow. I can't seem to understand which sidebar header arrow is being referred to.

**Comment by KiKaraage** [comment]
This one! The sidebar header title  and arrow are clickable and you can choose which panel to show or which side do you want sidebar on.
![2017-11-03-00-34-17-d11024](https://github.com/KiKaraage/ArcWTF/assets/10529881/8cb48021-ee39-4396-bce4-7bb4ccfd4331)

Though with the latest version of my theme, I showed the sidebar header by default (it wasn't happened before), and you can just click on it:
![gambar](https://github.com/KiKaraage/ArcWTF/assets/10529881/c2da5bb5-0107-4273-a8ba-60ee670a723e)

**Comment by Kshitij841** [comment]
Thank you so much! Love the theme, great work!
