### ISSUE TITLE
[BUG] Opening a context menu sometimes hangs the browser

### ISSUE THREAD

**Issue by asyncedd** [KiKaraage/ArcWTF#24]
Hello! I love your FirefoxCSS theme, in fact it is the first time in a long time to use a proper theme without applying extra tweaks from the FirefoxCSS-hacks (or something) repo myself. (that's how good it is!)

But, there is one regression that is making using this theme a pain in the ass. Sometimes, nay, most of the time if I try to open the context menu via pressing the right-button key, the whole Firefox UI freezes, albeit it showing up after a while. It doesn't happen when I don't use the theme.

NixOS, Hyprland (Wayland, shouldn't matter TBH), Firefox v123

**Comment by KiKaraage** [comment]
Also want to tag fellow Hyprland user @Enigma1309 to see if this issue happened over all Hyprland/Linux FF users.

**Comment by Enigma1309** [comment]
Okay, what do you mean by right button key? 
are you talking about key that is present near alt button? or talking about right click on mouse?
Either way i haven't came across any issues using those two
i've tested this on both firefox and librewolf now 
if i'm not wrong you're talking about this right?
![image](https://github.com/KiKaraage/ArcWTF/assets/94917588/49ebfb52-80af-4acb-ba97-64098f4a0133)

during my test all this seems to work right....
btw you're using flatpak? i tested this it on native repo apps

**Comment by asyncedd** [comment]
> Second.... edge-frfox, base of this theme, has `uc.tweak.revert-context-menu` to disable the custom Edge-themed context menu and use the default Firefox menus; you might want to apply it on about:config.

OK thanks, will-do for the time being

**Comment by asyncedd** [comment]
> Okay, what do you mean by right button key? are you talking about key that is present near alt button? or talking about right click on mouse? Either way i haven't came across any issues using those two i've tested this on both firefox and librewolf now if i'm not wrong you're talking about this right? ![image](https://private-user-images.githubusercontent.com/94917588/309800699-49ebfb52-80af-4acb-ba97-64098f4a0133.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1OTI3NTksIm5iZiI6MTcwOTU5MjQ1OSwicGF0aCI6Ii85NDkxNzU4OC8zMDk4MDA2OTktNDllYmZiNTItODBhZi00YWNiLWJhOTctNjQwOThmNGEwMTMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDIyNDczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxNGU2N2JmMTAyYzkzNjNiMzJhZTQ4YTM5MWJhZTViZjQzZTg0NWZlNmI0MGUxMmVmNjJhOTFmZmEyN2FjZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dwMcM6KpwkCX0YhxYkO1FlXl7CZ6FjKVZ8TMl4-emOc)

The context menu (the right click on the mouse, yes)

> during my test all this seems to work right.... btw you're using flatpak? i tested this it on native repo apps

No

**Comment by Enigma1309** [comment]
> > btw you're using flatpak?

>No

then it should work as expected

anyways try this 
- go to about:profiles
- create a new profile (it will be automatically defaulted, keep this in mind)
- launch it in new window, and see whether it's working or not
- observe and if possible a screen recording would be good.
- see if the problem persists
- you may delete the new profile if you want.

thank you

**Comment by asyncedd** [comment]
> anyways try this
> 
>     * go to about:profiles
> 
>     * create a new profile (it will be automatically defaulted, keep this in mind)
> 
>     * launch it in new window, and see whether it's working or not
> 
>     * observe and if possible a screen recording would be good.
> 
>     * see if the problem persists
> 
>     * you may delete the new profile if you want.
> 

It worked perfectly, thanks! I think my current profile got dirty somehow. Anyways, it's on my end. Sorry and thank you for helping my debug this!
