### ISSUE TITLE
Fullscreen with all ArcWTF interface

### ISSUE THREAD

**Issue by Mojas84** [KiKaraage/ArcWTF#31]
Hello. Would it be possible to add or fix the interface? because when I maximize ArcWTF, MyDockFinder application still shows me, and when I go full screen, the ArcWTF interface disappears, which I would rather see.....
![sshot-1](https://github.com/KiKaraage/ArcWTF/assets/108186899/4696daf0-bd32-473f-9111-cf28574084dd)

**Comment by KiKaraage** [comment]
I think you can try going on MyDockFinder settings first and if there's setting related to "Stay On Top", uncheck it, so that the dock doesn't interrupt your browsing experience
