### ISSUE TITLE
How can i stop the sideberry tab bar to hide?

### ISSUE THREAD

**Issue by ZakkyPatronu** [KiKaraage/ArcWTF#4]

**Comment by LuanderFarias** [comment]
click on the modified userchrome toggle buttton on the navbar. you can read the readme to learn how to set it up

**Comment by LuanderFarias** [comment]
also, i can hop on a call at discord with you if you want a video tutorial

**Comment by KiKaraage** [comment]
Please specify:
1. Have you install Userchrome Toggle addons, followed the direction on readme.md, and pin it on toolbar?
2. Are you running on Floorp? Because currently Userchrome Toggle is not working on Floorp, thus you're left with either a) autohidden sidebar that you can't pin, or b) pinned sidebar that aren't autohidden (but toggle-able with Firefox default sidebar button).

**Comment by Enigma1309** [comment]
You have to make this changes like this...if you have  installed Userchrome Toggle
![image](https://github.com/KiKaraage/ArcWTF/assets/94917588/2a3b8480-c2d5-4da5-bd58-765937d75d96)

Make sure the prefix have this `|| ` ( yes including space )

**Comment by ZakkyPatronu** [comment]
THANKS EVERYONE I FIXED IT!!!!

**Comment by slrgt** [comment]
@LuanderFarias do you know how I can make it so the sidebar always shows? I want the tabs on the top and the sidebar tabs at the same time always

**Comment by Enigma1309** [comment]
@slrgt install sideberry and import it's css on a normal browser it should work imo

**Comment by slrgt** [comment]
I tried :( no luck

**Comment by Enigma1309** [comment]
i just tried and it works, install sideberry in the new firefox/derivatives profile (`about:profiles`)
then just copy paste the contents of [this](https://github.com/KiKaraage/ArcWTF/blob/main/sidebery-css-style) file on the sideberry css editor; or more easily import the json file in sideberry/help  it should work
(the css file on repo seems outdated use the json method instead)

see

![image](https://github.com/KiKaraage/ArcWTF/assets/94917588/c122062b-97fb-4886-ac77-f099a315d3f0)

**Comment by slrgt** [comment]
@Enigma1309 I try this but as soon as I install sideberry the top bars dissapear unless I hide the sidebar. Even after going to help > Import addon data > and selecting the sidebery-Arc.json > All Settings Styles on and clicking import. If the sidebar is shown the top tabs are hidden

**Comment by slrgt** [comment]
Here's a video of what happens
https://github.com/KiKaraage/ArcWTF/assets/114287507/706c9810-50d9-45ae-9f0e-7414f35245fc

**Comment by slrgt** [comment]
Here's a video of what happens
https://github.com/KiKaraage/ArcWTF/assets/114287507/582e83d8-cd4c-4ce6-9c5a-7b03a837b45a

**Comment by Enigma1309** [comment]
you are following every step..just install sideberry in new profile and import it's json it should work and also user-chrome toggle isn't needed if you want both at the same time

**Comment by slrgt** [comment]
Im trying but i cant get it to work. I made a new profile, installed sidebery, exported the addon data in the Help section and then imported it but it stays with the hiding behavior :(

**Comment by slrgt** [comment]
If i delete sidebar.css and hidebar.css from Chrome>Tweaks then it works
I just need to find out how to remove this part so it doesnt look so ugly
![ShareX_wlbvommPgz](https://github.com/KiKaraage/ArcWTF/assets/114287507/d672f53a-8be4-4069-beda-91a81352ec2c)

**Comment by Enigma1309** [comment]
i'm not too sure about it you may lookup on internet or r/firefoxcss
