### ISSUE TITLE
How to always keep sidebar opened, and hide with a key press?

### ISSUE THREAD

**Issue by LupuC** [KiKaraage/ArcWTF#42]
I've set everything up, and works fine. Now, I want to Hide the sidebar (f1 key right now). If I press to hide it, it will hide, then the top navbar will appear. If I press again f1, it will hide the top navbar, and the sidebar now has to be hovered to be shown...

https://github.com/KiKaraage/ArcWTF/assets/62475718/fbb4ea2e-de7c-483f-b3a5-6dab51aa6cf2

**Comment by LupuC** [comment]
I'm curious why did you implement userchrome toggle instead of leaving the native toggle of the navbar..

**Comment by KiKaraage** [comment]
Solution: Set keyboard shortcut for Userchrome Toggle instead of Sidebery.

If you want to use F1 for toggling the sidebar, you have to assign another shortcut first for Sidebery (Go to about:addons, click the gear icon in top right corner, choose Manage Extensions Shortcuts, scroll to Sidebery, assign other key. I use F3)

And then, you can assign F1 for Userchrome Toggle

So, when toggling the Userchrome Toggle button, you can switch between hidden sidebar (that can be hovered to show sidebar fully, temporary) and static sidebar

**Comment by KiKaraage** [comment]
> Why did you implement userchrome toggle instead of leaving the native toggle of the navbar?

I use Userchrome Toggle because by using it I can make the sidebar autohidden (**and shown when hovered**), like how it works on Arc. 

Otherwise if I only use native sidebar button, the sidebar state would only be "hidden permanently" or "shown permanently"

**Comment by LupuC** [comment]
I see. Thanks for the help, I might work for a workaround to only have the sidebar, without Userchrome Toggle, because personally, i don't use that show on hover feature.

**Comment by hdubbs** [comment]
> I see. Thanks for the help, I might work for a workaround to only have the sidebar, without Userchrome Toggle, because personally, i don't use that show on hover feature.

I'd also be interested in this, since I prefer to work with a keyboard.

**Comment by LupuC** [comment]
> > I see. Thanks for the help, I might work for a workaround to only have the sidebar, without Userchrome Toggle, because personally, i don't use that show on hover feature.
> 
> 
> 
> I'd also be interested in this, since I prefer to work with a keyboard.

Check this out:

https://github.com/LupuC/FlowUI_firefox

**Comment by KiKaraage** [comment]
> Check this out: https://github.com/LupuC/FlowUI_firefox

Would love to see some screenshots!

**Comment by LupuC** [comment]
> > Check this out: https://github.com/LupuC/FlowUI_firefox
> 
> Would love to see some screenshots!

Check the repo again ;)
