### ISSUE TITLE
the addon seems to be corrupt (v123)

### ISSUE THREAD

**Issue by NDSTHEBEST** [KiKaraage/ArcWTF#57]
i tried to upload the extension but its not working. it says the addon is corrupt.

it also gave me this error when I'm trying to debug it:
File C:\Users\noamd\Downloads\Compressed\ArcWTF-main.zip does not contain a valid manifest

it tried librewolf, waterfox, and even firefox itself, but its not working - the d=same error in all of them!

please help me

**Comment by Kribbage** [comment]
it isn't an addon, you have to follow the instructions in the readme to find your profile folder.
