### ISSUE TITLE
How to disable the borders?

### ISSUE THREAD

**Issue by slrgt** [KiKaraage/ArcWTF#59]
Hi, I love this theme but I would like to remove the borders on the left, bottom, and right of the screen. I want to maximize my screen real estate :)

**Comment by Orbsa** [comment]
This could be an issue with your browser. I had this issue with librewolf
Check the flag "privacy.resistFingerprinting.letterboxing" and ensure it is disabled

**Comment by slrgt** [comment]
I mean the borders that the theme adds

**Comment by slrgt** [comment]
open the user profile root folder and go to Chrome > global >browser.css in line 46 you can change the size of the borders by changing the number next to px
