### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by ShreyasK06** [KiKaraage/ArcWTF#6]
I have everything downloaded but it still doesn't work on windows 11

**Comment by KiKaraage** [comment]
Have you done all of the steps?
1. Install Sidebery and Userchrome Toggle
2. Go to Add-ons Manager, choose Userchrome Toggle, go to Options, type "|| " in **prefix**, apply changes. And Pin to Toolbar too
![gambar](https://github.com/KiKaraage/ArcWTF/assets/10529881/ab412886-f9cf-45ea-8a26-c1654c3cc5a2)
![gambar](https://github.com/KiKaraage/ArcWTF/assets/10529881/219d5c96-fe6e-489f-a55d-e8ad88798046)
3. [Download](https://github.com/KiKaraage/ArcWTF/releases/tag/v1.1-firefox) and extract the theme files
4. Open `about:profiles` in Firefox, open Root Directory folder
![gambar](https://github.com/KiKaraage/ArcWTF/assets/10529881/a31c937c-4f03-4bad-a211-1af4694c258a)
6. go to "chrome" folder and paste the theme folders + files there
![gambar](https://github.com/KiKaraage/ArcWTF/assets/10529881/35dc74da-ca94-4279-845b-36f9c4cc3267)
7. Open `about:config` in Firefox, type `toolkit.legacyUserProfileCustomizations.stylesheets`, choose Boolean, click **+**
8. Clear the text field, then type `svg.context-properties.content.enabled`, choose Boolean, click **+** too
9. Restart Firefox (you can do this from `about:profiles`)
10. After Firefox restarted, you can go to Customize Toolbar menu, move buttons and add flexible spaces
11. And then you can go to Sidebery settings (extensions > right click Sidebery icon > open settings), go to Style Editor, paste the [CSS code](https://github.com/KiKaraage/ArcWTF/blob/main/sidebery/sidebery-css) or go to Help and click Import addon data, choose the [JSON file](https://github.com/KiKaraage/ArcWTF/blob/main/sidebery/sidebery-ArcWTF.json)
![gambar](https://github.com/KiKaraage/ArcWTF/assets/10529881/f89634a1-9775-4e00-92bd-db3960248832)
![gambar](https://github.com/KiKaraage/ArcWTF/assets/10529881/083518b0-ea9d-4784-87c9-b1b66cb26c09)
![gambar](https://github.com/KiKaraage/ArcWTF/assets/10529881/ac423580-d8cd-4f9b-ad93-1247ba3682bd)

**Comment by mrnicemann123** [comment]
same problem for me with Windows 11, i have tried Firefox 123 and 124, and it doesn't work for me
