### ISSUE TITLE
[Question] how to prevent userchrome toggle shifting the whole page

### ISSUE THREAD

**Issue by noidilin** [KiKaraage/ArcWTF#62]
Since I prefer a keyboard-driven browsing experience, I use a userchrome shortcut to toggle the sidebar visibility instead of hovering over the sidebar area. Although this method works well for my goal, there is an annoying shift on my whole page every time the userchrome is toggled.

I noticed that using the mouse to hover over the sidebar can prevent this behavior. Therefore, I would like to know if there is any way to use a keyboard shortcut to display the sidebar, just like the mouse-hovering behavior.

**Comment by ArtemChandragupta** [comment]
Hi. What shortcut do you use for that?

**Comment by noidilin** [comment]
I config my keybinding as the suggestion in the [issue#55](https://github.com/KiKaraage/ArcWTF/issues/55).

I haven't try out the new recommended extension in the latest reply. I currently using two keybinding to toggle the expand and collapses state, which are <Ctrl + Shift + 1> and <Ctrl + Shift + 2> respectively.

**Comment by ArtemChandragupta** [comment]
You need to do it the other way, because this is identical to tapping on the userchrome icon. Layered sidebar is different, and a way to summon it should be in chrome folder as I guess, but I can't find it.

Userchrome extended will summon the same menu as you get by tapping on userchrome icon.
