### ISSUE TITLE
[Styling question] Transparent frame

### ISSUE THREAD

**Issue by ArtemChandragupta** [KiKaraage/ArcWTF#65]
Hi! 
I am not very familiar with firefox styling, but is there a way to make outer frame transparent to match my terminal theme?
I use Linux, Hyprland. Tried firefox-colors, but It can't create transparent color for tab bar.
![swappy-20240622_143226](https://github.com/KiKaraage/ArcWTF/assets/90765302/c15fb84a-1b1c-499d-aadc-5cf8a00742ee)

**Comment by asyncedd** [comment]
not use a theme, see: https://github.com/KiKaraage/ArcWTF/issues/53

it's more a bug than a feature though

**Comment by ArtemChandragupta** [comment]
It will be possible with new firefox release on 3 September.
