### ISSUE TITLE
Blinking Cursor everywhere

### ISSUE THREAD

**Issue by jahusa02** [KiKaraage/ArcWTF#70]
Everywhere I click I get a blinking cursor. Even in DevTools

Win 11
Firefox 127.0.1

Followed the instructions on Github
sha: bb6f2b7ef7e3d201e23d86bf8636e5d0ea4bd68b

**Comment by AngelCMHxD** [comment]
That's probably carret browsing, you can toggle it with F7 and it's a firefox feature (well, all browsers I know have this feature) :P
