### ISSUE TITLE
No zoom indicator

### ISSUE THREAD

**Issue by D3SOX** [KiKaraage/ArcWTF#81]
With stock Firefox, there's an indicator when you're not zoomed to 100%. I can't seem to find it with the theme applied.

**Comment by KiKaraage** [comment]
Delete [line 172 from urlbar.css](https://github.com/KiKaraage/ArcWTF/blob/73ccc7bd3c8dd130d67746c413ca5cf6a57a9f72/toolbar/urlbar.css#L172)!

As someone who set 80% as default zoom, the persistent zoom indicator is annoying to me - hence why I hide it by default here. Recently I tried Arc again and their approach to zoom, displaying our current zoom level just as a tooltip/timed popup, is so much better ahaha
