### ISSUE TITLE
No sidebar bookmarks like arc?

### ISSUE THREAD

**Issue by weekendweekender** [KiKaraage/ArcWTF#82]
Just want to know if this feature is available. I tried to use pinned tabs as bookmarks but the browser loads all the pinned tabs when reopened and they stay there when I want so switch to different spaces (tab panel).

**Comment by KiKaraage** [comment]
Wait I don't understand. Would you like to elaborate more about what you did in Sidebery vs how it work on Arc?

**Comment by weekendweekender** [comment]
I meant to ask if there is a way to have tabs bookmarked on the same panel as the current tabs. Arc has this separator where if you bookmark a tab it goes into the upper section of the space (tab panel). I've been using pinned tabs on Sidebery as bookmarks, but the problem is that they load automatically every time I open Firefox.
![image](https://github.com/user-attachments/assets/0d009ea9-0230-46d1-9aef-56ba33b8cdf1)
Check the attached image taken from Arc's sidebar, the tabs and folders above the 1px border are bookmarked tabs which stay only on the current space (CODE). The two boxed tabs above it with the Google logo and Google translate are pinned tabs which are there on every space.

**Comment by KiKaraage** [comment]
You can group/put tabs in folder and use it as sort of "bookmarks" in Sidebery if you want to replicate that look!

Though tab management on Arc is very different than in Firefox (even with Sidebery). In Firefox, you can't divide tabs into three category (pinned tabs - persistent "bookmark" tabs - auto-purged temporal tabs)... only pinned tabs and non-pinned tabs. Either you keep the session and have the same tabs (albeit on sleep mode) each time you open Firefox, or leave non-pinned tabs purged with each session closing. 

![image](https://github.com/user-attachments/assets/d7180621-4299-46aa-8f9e-802bda1907fd)

**Comment by weekendweekender** [comment]
Hey, thanks that worked out! Also is there a shortcut to switch between tab panels?

**Comment by KiKaraage** [comment]
Of course! Sidebery has **105 possible shortcuts** to choose hahaha
![image](https://github.com/user-attachments/assets/6981e58f-0282-4479-b50a-02f1ef7dc093)

**Comment by weekendweekender** [comment]
Thanks! I appreciate how helpful you've been. I wish you good luck!
